
replicaCount: 1

image:
  repository: ealen/echo-server 
  pullPolicy: Always 
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
nameOverride: "echo"
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "kong-external"
  #annotations: 
  #  kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: da.com 
      paths:
        - path: /echo
          pathType: Prefix
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80