apiVersion: v1
kind: Service
metadata:
  name: konga-service
spec:
  selector:
    app: konga
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
        - name: konga
          image: pantsel/konga:latest
          ports:
            - containerPort: 1337
          livenessProbe:
            httpGet:
              path: /register # Replace with the actual health check endpoint if Konga has one
              port: 1337
            initialDelaySeconds: 30 # Number of seconds after the container has started to wait before running the first probe
            periodSeconds: 10 # How often (in seconds) to perform the probe
            timeoutSeconds: 5 # Number of seconds after which the probe times out
            failureThreshold: 3

