---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.repoBranch }}
    path: {{ .Values.clusterName }}/namespaces/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
  - kind: Service
    jsonPointers:
    - /spec/selector